### ISSUE TITLE
Disable progress bar in bfcrpath

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocFileCache#13]
As requested by @lshep: currently, `bfcrpath` prints out a progress bar, which is nice in interactive sessions but annoying when compiling Rmarkdown documents. Ideally this could be turned off - or even better, diverted to the "message" stream so that _knitr_ automatically knows that it is not the output of a function and ignores it.

**Comment by lshep** [comment]
What sort of settings do you have in your vignette that knitr doesn't automatically pick it up?  We certainly can have it divert but in its current state when I knitr a vignette it doesn't show the progress bar as part of the output already and when I run a non interactive session it also does not show the progress bar.  So is there a more specific case you are seeing this appear?

**Comment by lshep** [comment]
Thanks -   looks like it specifically happens when using rmarkdown::render -  When I tried this script and used Rstudio's provided knit function the output did not include the progress bar -  now that I can reproduce I'll look at a fix
