### ISSUE TITLE
example(bfcmeta) can throw error

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/BiocFileCache#15]
eventually we get to
```
bfcmet> bfcsync(bfc0)
entries without corresponding files: 'BFC1'
delete 1 entries? (yes/no): yes
[1] TRUE

bfcmet> bfcremove(bfc0, "BFC1")
Error in bfcremove(bfc0, "BFC1") : all(rids %in% bfcrid(x)) is not TRUE

Enter a frame number, or 0 to exit   

1: example(bfcmeta)
2: source(tf, local, echo = echo, prompt.echo = paste0(prompt.prefix, getOptio
3: withVisible(eval(ei, envir))
4: eval(ei, envir)
5: eval(ei, envir)
6: Rex18361745a3823#91: bfcremove(bfc0, "BFC1")
7: bfcremove(bfc0, "BFC1")
8: stopifnot(all(rids %in% bfcrid(x)))
```  

I am trying to explain use of bfc to a developer and ?bcfmeta leads to a nonspecific, thorough but overly long man page.  The use cases in the vignette are good and need careful study by prospective users.

**Comment by lshep** [comment]
Thanks for reporting this -  I'll look into the vignette examples and try to track it down.  

we thought it better practice to have the class and all the accessor methods documented on one page but that leads to a long man page.

**Comment by lshep** [comment]
Fixed with some comments.   If not in interactive mode BiocFileCache doesn't allow you to destroy your cache (unless ask=FALSE) which is why the manual remove after - but if a user ran the code they probably decided to fix with the sync command 
Cheers,
