### ISSUE TITLE
file comparison only on Date will miss updates on edge case of same day  updates

### ISSUE THREAD

**Issue by lshep** [Bioconductor/BiocFileCache#17]
Rare case that more than one update in a day will result in not updating the cache - 

```
Browse[3]> as.Date(web_time, optional=TRUE)
[1] "2019-04-15"
Browse[3]> as.Date(file_time, optional=TRUE)
[1] "2019-04-15"
```
But
```
Browse[3]> file_time
                 BFC1 
"2019-04-15 13:21:17" 
Browse[3]> web_time
[1] "2019-04-15 13:51:17"

```
Can comparison include  hour/min/sec?

**Comment by lshep** [comment]
res <- as.Date(web_time, optional=TRUE) >
                        as.Date(file_time, optional=TRUE)

https://github.com/Bioconductor/BiocFileCache/blob/master/R/BiocFileCache-class.R#L1002

**Comment by lshep** [comment]
@mtmorgan   What about updating as.Date to as.POSIXlt  ?   or should we not worry about this edge case? 
This would not pick up updates if say a remote file was updated,  a user ran the code to redownload,  then the remote file was updated again on the same day -  when the user runs the code again it would not pick up an out-of-date file because it only recognizes the month-day-year and not full time stamp

```
> file_time = "2019-04-15 13:21:17"
>  web_time = "2019-04-15 13:51:17"

# Is what we get but really should be TRUE
> as.Date(web_time, optional=TRUE) > as.Date(file_time, optional=TRUE) 
[1] FALSE


> as.POSIXlt(web_time) >  as.POSIXlt(file_time)
[1] TRUE

> file_time=web_time
> as.POSIXlt(web_time) >  as.POSIXlt(file_time)
[1] FALSE
```
I believe it would just be a one line change at:  https://github.com/Bioconductor/BiocFileCache/blob/master/R/BiocFileCache-class.R#L1002

**Comment by lshep** [comment]
For the record - picked this up doing local testing on the hubs -  I was adding groups of data separate since I had about 6 different hub datasets to add but wanted to do it step by step to ensure no errors - so after I updated once per day I wouldn't get an updated cache unless I manually did a bfcdownload -

**Comment by mtmorgan** [comment]
yes I think you should make this change.
