### ISSUE TITLE
Allow user-supplied rid?

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/BiocFileCache#2]
It would be useful to allow the user to supply the rid. In the case of files coming from public repositories, uuids and accessions are the most useful and meaningful identifiers. This information can be placed in rname, but that is mutable, allowing a "user" to mess with the primary key established by the "developer". 

My concrete use case is to use the GDC file uuid as the rid.

**Comment by lshep** [comment]
The code is designed to have unique identifiers for the BiocFileCache database. As you identified, the "rname" or adding additional metadata for the resource would be the best place for this information.  If the idea is to supply a BiocFileCache to the "user" and this information needs to be more secure, we would recommend providing an intermediate interface not exposing the accessor methods for these columns.
