### ISSUE TITLE
tests fail due to stats URL 404ing

### ISSUE THREAD

**Issue by mr-c** [Bioconductor/BiocFileCache#20]
http://bioconductor.org/packages/stats/bioc/BiocFileCache/BiocFileCache_stats.tab is missing

therefore `tests/testthat/test_BiocFileCache_class.R`'s "bfcdownload works" test fails

**Comment by lshep** [comment]
We are aware and are fixing the issue with the stats being available.

**Comment by mr-c** [comment]
http://bioconductor.org/packages/stats/bioc/BiocFileCache/BiocFileCache_stats.tab is back up ; thanks!
