### ISSUE TITLE
Deprecated dplyr functions cause check warnings

### ISSUE THREAD

**Issue by tfkillian** [Bioconductor/BiocFileCache#23]
I maintain the [Depmap](https://github.com/UCLouvain-CBIO/depmap) package which depends downstream on BiocFileCache.  I have been working on updating the Depmap package to be in line with the new [dplyr 1.0 release changes](https://github.com/tidyverse/dplyr/blob/master/NEWS.md). Despite making all the necessary code changes, a check warning appeared (see code below) which I have traced back to the [sql.R file in this package](https://github.com/Bioconductor/BiocFileCache/blob/master/R/sql.R), which imports select_ and filter_ functions which will soon be deprecated with the dplyr 1.0 release, and thus responsible for the warning.

```
* checking whether package 'depmap' can be installed ... WARNING
Found the following significant warnings:
  Warning: `select_()` is deprecated as of dplyr 0.7.0.
  Warning: `filter_()` is deprecated as of dplyr 0.7.0.
```

Do you plan to update these functions with their non-deprecated dplyr 1.0 versions?

```
#' @importFrom dplyr %>% tbl select_ collect summarize filter_ n left_join
```

**Comment by lshep** [comment]
Thank you for pointing this out.  We were recently made aware and will look at updating BiocFileCache.
