### ISSUE TITLE
Is BiocFileCache's directory structure "scratch-safe"?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocFileCache#28]
In many HPC environments, we have scratch storage where files are deleted after they have not been accessed for X days. This provides quota-free data usage without the cost of accumulating a bunch of crud. For one of my applications, I've thought about setting its dedicated BiocFileCache instance to live in the scratch space. This would mean that I could put large files in there without worrying about the space limits in the user's home directory. 

However, it also means that files will just randomly disappear over time. I am fine with this, as I can write checks for whether the file path exists and redownload it if it vanished. I also assume that the SQLite file will not be deleted as it is touched upon any access; or specifically, if it does get deleted, it should be the last thing in the cache to go. At that point the folder does not exist as a meaningful cache anymore and I can just recreate it without much consequence.

The questions I have are:

- Is this safe? Are there any other files expected by BFC that might be lost by the scratch policy?
- Is this actually effective? Does **BiocFileCache** touch files beyond the SQLite file in routine operations?

**Comment by lshep** [comment]
I'd rather not get into the debate of is it safe... It should be true that the only relevant file is the sqlite file and files could be recoverable from the sqlite file.

**Comment by LTLA** [comment]
Okay, as long as the only relevant file is the sqlite file, we should be okay.
