### ISSUE TITLE
tools::R_user_dir vs rappdirs::user_cache_dir

### ISSUE THREAD

**Issue by lgeistlinger** [Bioconductor/BiocFileCache#29]
Hi Lori, I was wondering whether it would make sense to use `tools::R_user_dir(which = "cache")` (introduced in R-4.0.0) for `BiocFileCache`'s default cache directory to strip off the `rappdirs` dependency? Just a thought.

**Comment by lshep** [comment]
Yes. thank you for reminding me that this was added into tools. I'll look into updating to lighten the dependency structure.  Cheers!

**Comment by lshep** [comment]
We have just pushed changes that will implement this. See [committ](https://github.com/Bioconductor/BiocFileCache/commit/c093897348b7431ef8a3405b89dfbf71f36a37fb)   Note:  rappdirs currently remains in the dependency structure and will for at least one release cycle to help notify users of the location change.  It will be removed completely in either 3.14 or 3.15  release.

**Comment by lgeistlinger** [comment]
Thanks @lshep !

**Comment by lgeistlinger** [comment]
Just stumbled over this again and wondered whether the time is here to get rid of `rappdirs`.

**Comment by lshep** [comment]
@vjcitn  / @mtmorgan   thoughts?  perhaps at the start of the next release remove it completely in the devel branch?
