### ISSUE TITLE
Allow "pluggable" download option and update checking for remote resources

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/BiocFileCache#3]
For some applications, the URL is not all that is needed to do a download of a remote resource. For example, one might need to do some authentication first, supply a token as a parameter, or even have a tool that does the download outside of R. Again, my concrete use case is the need to supply a token with the download as an http header and to potentially use an external tool (gdc downloader) to do the downloads. 

I can certainly do all the work outside of biocfilecache and then add resources as local resources, so this isn't a high priority, but I thought I would bring it up to see what you thought.

**Comment by lshep** [comment]
Would exposing the httr::GET argument config be sufficient in achieving this?

**Comment by lshep** [comment]
@seandavi  would exposing the httr::GET argument config be sufficient?

**Comment by lshep** [comment]
exposed config of GET.

**Comment by lshep** [comment]
also exposed '...' of GET  in 1.3.38
