### ISSUE TITLE
Update remote file only when changed

### ISSUE THREAD

**Issue by chrarnold** [Bioconductor/BiocFileCache#37]
I am struggling a bit with using BiocFileCache in a package context to cache package-related data. What I want is: For the examples in my R code, I need to first download a small example object that should be cached so it can be retrieved quickly when building the package etc. I want to program it in a way that every modification of the file on the remote site automatically triggers a re-download when using BioFileCache. I used the template here: https://bioconductor.org/packages/release/bioc/vignettes/BiocFileCache/inst/doc/BiocFileCache.html#cache-to-manage-package-data

Quetsions:
1. `bfcneedsupdate(bfc, rid)` always returns TRUE and re-downloads the file when executed.  Shouldnt it only return TRUE when an update is needed?
2. How to make it work that it re-downloads automatically when the remote file has been modified? I thought this should be the default behavior, but I can't judge whether this works out of the box given my problem in (1).
3. Do I have to adjust anything in the template that is given? What, for example, is `geneFileV2` meant to be or represent? Just an arbitrary name for the file that should be cached as used in the database?

Thank you,
Christian

**Comment by lshep** [comment]
It should return TRUE only when the file needs updating. I'll look into this right away. 
It should automatically recognize a change and download but only when necessary. 
When you cache the file you could give it a unique rname, by default will use the url. Think of rname like a title. GeneFile2 shown would be a unique rname to retrieve the resource.

**Comment by chrarnold** [comment]
Hi there! Ok I see, then, as I thought, BiocFileCache should work exactly as I hoped right out of the box :). I wonder what happens for me then, maybe  am misunderstanding something: After downloading the file with BiocFileCache, I thought that `bfcneedsupdate(bfc, rid)` would rturn FALSE after, indicating a download is not necessary. This is what doesnt seem to work for me:

`
> BiocFileCache::bfcneedsupdate(bfc, rid)
BFC1 
TRUE 
>     filePath = BiocFileCache::bfcdownload(bfc, rid, ask = FALSE)

> BiocFileCache::bfcneedsupdate(bfc, rid)
BFC1 
TRUE `

**Comment by chrarnold** [comment]
Hi there! Ok I see, then, as I thought, BiocFileCache should work exactly as I hoped right out of the box :). I wonder what happens for me then, maybe  am misunderstanding something: After downloading the file with BiocFileCache, I thought that `bfcneedsupdate(bfc, rid)` would rturn FALSE after, indicating a download is not necessary. This is what doesnt seem to work for me:

**Comment by chrarnold** [comment]
Hi there! Ok I see, then, as I thought, BiocFileCache should work exactly as I hoped right out of the box :). I wonder what happens for me then, maybe  am misunderstanding something: After downloading the file with BiocFileCache, I thought that `bfcneedsupdate(bfc, rid)` would rturn FALSE after, indicating a download is not necessary. This is what doesnt seem to work for me:

`
> BiocFileCache::bfcneedsupdate(bfc, rid)
BFC1 
TRUE 
>     filePath = BiocFileCache::bfcdownload(bfc, rid, ask = FALSE)

> BiocFileCache::bfcneedsupdate(bfc, rid)
BFC1 
TRUE `

**Comment by lshep** [comment]
Would you mind sharing the url of the file you're downloading?

**Comment by chrarnold** [comment]
Sure! Here is literally my code that - at least on my machine (Ubuntu) - displays the behavior I described (I just tested again:)

`loadExampleObject <- function(forceDownload = FALSE, fileURL = "https://www.embl.de/download/zaugg/GRaNIE/GRN.rds") {
  
  checkmate::assertFlag(forceDownload)
  # Taken and modified from https://www.bioconductor.org/packages/release/bioc/vignettes/BiocFileCache/inst/doc/BiocFileCache.html
  
  bfc <- .get_cache()
  
  rid <- BiocFileCache::bfcquery(bfc, "GRaNIE_object_example")$rid
  if (!length(rid)) {
    rid <- names(BiocFileCache::bfcadd(bfc, "GRaNIE_object_example", fileURL))
  }
  if (!isFALSE(BiocFileCache::bfcneedsupdate(bfc, rid)) | forceDownload) {
    messageStr = paste0("Downloading GRaNIE example object from ", fileURL)
    message(messageStr)
    filePath = BiocFileCache::bfcdownload(bfc, rid, ask = FALSE)
  }
  
  
  filePath = BiocFileCache::bfcrpath(bfc, rids = rid)
  
  # Now we can read in the locally stored file
  readRDS(filePath)
  
}
`

When I execute the following line multiple times, I always see the downloading message anew because `BiocFileCache::bfcneedsupdate(bfc, rid)` evaluates to TRUE all the time it seems. I greatly appreciate your thoughts here, thank you:

**Comment by lshep** [comment]
The reason why the file always returns TRUE for needs update is actual an issue with the header information of the fileURL.  We grab header information for expires, last-modified, and etag to determine when a resource needs to be redownloaded.  The expires field of the header from the url always returns expired 

```
> cache_info(HEAD(fileURL))
<cache_info>  https://www.embl.de/download/zaugg/GRaNIE/GRN.rds
  Cacheable:     TRUE
  Expires:       Mon, 21 Mar 2022 13:13:06 GMT <expired>
  Last-Modified: Fri, 18 Mar 2022 20:50:00 GMT
  Etag:          "47cc041-5da844a462490"
> cache_info(HEAD(fileURL))
<cache_info>  https://www.embl.de/download/zaugg/GRaNIE/GRN.rds
  Cacheable:     TRUE
  Expires:       Mon, 21 Mar 2022 13:13:08 GMT <expired>
  Last-Modified: Fri, 18 Mar 2022 20:50:00 GMT
  Etag:          "47cc041-5da844a462490"
> cache_info(HEAD(fileURL))
<cache_info>  https://www.embl.de/download/zaugg/GRaNIE/GRN.rds
  Cacheable:     TRUE
  Expires:       Mon, 21 Mar 2022 13:13:10 GMT <expired>
  Last-Modified: Fri, 18 Mar 2022 20:50:00 GMT
  Etag:          "47cc041-5da844a462490"

```

**Comment by chrarnold** [comment]
Interesting, thanks for digging into it! Any idea what the reason for this could be? This is a folder we can use for publicly accessible URLs, anything I can do to change the expiration date somehow?

**Comment by lshep** [comment]
Also even if there is a way to exclude the expires field or have it as NA will work because it only compares to data available.
