### ISSUE TITLE
bfcquery[['rpath']] is not the same as bfcrpath()

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocFileCache#38]
Hi Lori, @lshep 

Perhaps it was designed this way but the code in `AnnotationForge` was assuming that `bfcquery(...)[["rpath"]]` is identical to `bfcrpath(...)`, i.e. the file path to the resource.
It currently returns the `basename()` of the resource; perhaps this was done to shorten the display in the return of `bfcquery`? 

I believe `rpath` to the user should be consistent throughout whether one obtains it from `bfcquery` or `bfcrpath`.

Thanks!

``` r
suppressPackageStartupMessages({
    library(BiocFileCache)
})
fullUri <- "http://www.uniprot.org/uniprot/?query=P13368+or+Q6GZX4&format=tab"
bfc <- BiocFileCache()
## First time around works fine downloads file
uquery1 <- bfcquery(bfc, query = fullUri, exact = TRUE)[["rpath"]]
if (!length(uquery1))
    uquery1 <- BiocFileCache::bfcadd(bfc, fullUri, fullUri)
uquery1
#>                                                                                            BFC35 
#> "/home/user/.cache/R/BiocFileCache/5b2435c9426a_%3Fquery%3DP13368%2Bor%2BQ6GZX4%26format%3Dtab"

## Second time around the query returns the basename of uquery1
(uquery2 <- bfcquery(bfc, query = fullUri, exact = TRUE)[["rpath"]])
#> [1] "5b2435c9426a_%3Fquery%3DP13368%2Bor%2BQ6GZX4%26format%3Dtab"

identical(uquery1, uquery2)
#> [1] FALSE
identical(basename(uquery1), uquery2)
#> [1] TRUE

identical(bfcrpath(bfc, fullUri, exact = TRUE), uquery1)
#> [1] TRUE
bfcremove(bfc, bfcquery(bfc, fullUri, exact = TRUE)[["rid"]])
```

<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lshep** [comment]
I'm looking into the changes for speed up we made to bfcquery to see if it was an unintended change but paths should probably be retrieved using the built in bfcrpath or bfcpath functions.

**Comment by LiNk-NY** [comment]
Thanks for looking into it! 
Perhaps this difference should be noted in the documentation and/or shown in the examples section.

Best,
Marcel
