### ISSUE TITLE
Using file hash instead of last modified time to check for cached file 

### ISSUE THREAD

**Issue by lcougnaud** [Bioconductor/BiocFileCache#5]
Have you considered of using file hash rather than the last modified date to check if (last downloaded) cached file is similar to new downloaded file?

**Comment by lshep** [comment]
This is added in devel.  Version >= 1.3.19.

The etag and the last modified time are utilized.  The etag is checked first and if available used to determine if a file needs to be updated.  If the etag is not available, than the last modified time is used.  If neither is available it is undetermined.
