### ISSUE TITLE
Default path on Windows not usable

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/BiocFileCache#6]
Using `BiocFileCache()` causes following error on Windows 10 64 bit 16299.192:

```
Error in rsqlite_connect(dbname, loadable.extensions, flags, vfs) : 
  Could not connect to database:
unable to open database file
In addition: Warning message:
In dir.create(cache) :
  cannot create dir 'C:\Users\username\AppData\Local\BiocFileCache\BiocFileCache\Cache', reason 'No such file or directory'
```
I think this is due to not having the correct privileges, but I didn't test it further.

`BiocFileCache("~/.BiocFileCache")` works as intended by creating using the directory `C:\Users\username\Documents\.BiocFileCache`. This behavior differs from the one described in the vignette under 1.2 as far as I understand. The default location `~/.BiocFileCache` is not used, if no path is given.

I didn't test it under any Linux, but I think this might be a Windows only issue.

**Comment by lshep** [comment]
The vignette is not entirely accurate, the default directory is .BiocFileCache in a user's cache directory as defined by `rappdirs::user_cache_dir()`  not  `~/`;  I'll update the vignette but it is accurately described in the man page.  If that directory is not accessibly do to permission, it would have to be manually input as you have done above to a directory that is writable.

**Comment by FelixErnst** [comment]
Thanks for the clarification. Nonetheless, the call to `dir.create`, which probably looks like this `dir.create(rappdirs::user_cache_dir(appname = "BiocFileCache"))`, does not create the directory.

I ran a short test: `dir.create(rappdirs::user_cache_dir(appname = "BiocFileCache"),recursive = TRUE)` works. I don't know, if somethings speaks against setting `recursive = TRUE`. 

So it is not a permission problem, but the functionality of dir.create does not allow the full path to be created, if the default `recursive = FALSE` is set, if more than the last level of directories does not exist. Is that Windows specific?

**Comment by lshep** [comment]
May I ask what version of the package you are using?  I did include a recursive call in version 1.3.23 so any version there after should have recursive = TRUE in the dir.create call.

**Comment by FelixErnst** [comment]
I am sorry for the trouble. Wrong VM loaded, not devel, so version BiocFileCache 1.2.1, which explains everything.

**Comment by lshep** [comment]
Thank you for pointing that out tho. The directory being created recursively is probably considered a bug fix that should go into release.  I will push a fix that should be available in the next day or two.

**Comment by lshep** [comment]
Please look for 1.2.2 -  it will have the recursive call included.  It is available through this github directory and should be available via biocLite in the next 24-48 hours.

**Comment by FelixErnst** [comment]
Thank you very much!
