### ISSUE TITLE
Cached files should remember 'Expires' / 'Max-age' headers

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocFileCache#8]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html section 14.21 says that Expires (possibly over-ridden by Max-age) can determine when a cached resource becomes out-of-date, but BFC doesn't remember Expires (or Date + Max-age) when the resource is downloaded, so can't know to update the resource.

**Comment by lshep** [comment]
included in 1.3.36 - also added bfcmigration function for older schema
